services:
  order-db:
    image: postgres:15
    container_name: order_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tharun@08
      POSTGRES_DB: order_db
    ports:
      - "5435:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - bookstore-network

  order-service:
    build: .
    container_name: order_service
    restart: on-failure
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:Tharun%4008@order-db:5432/order_db
      - BOOK_SERVICE_URL=http://book-service:8000
    depends_on:
      - order-db
    networks:
      - bookstore-network

volumes:
  order_db_data:

networks:
  bookstore-network:
    external: true