services:
  auth-db:
    image: postgres:15
    container_name: auth_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tharun@08
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - bookstore-network

  auth-service:
    build: .
    container_name: auth_service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:Tharun%4008@auth-db:5432/auth_db
    depends_on:
      - auth-db
    networks:
      - bookstore-network

volumes:
  auth_db_data:

networks:
  bookstore-network:
    external: true