services:
  book-db:
    image: postgres:15
    container_name: book_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tharun@08
      POSTGRES_DB: book_db
    ports:
      - "5434:5432"
    volumes:
      - book_db_data:/var/lib/postgresql/data
    networks:
      - bookstore-network

  book-service:
    build: .
    container_name: book_service
    restart: on-failure
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:Tharun%4008@book-db:5432/book_db
    depends_on:
      - book-db
    networks:
      - bookstore-network

volumes:
  book_db_data:

networks:
  bookstore-network:
    external: true